In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
X_train=torch.tensor(X_train,dtype=torch.float32)
X_test=torch.tensor(X_test,dtype=torch.float32)

<ipython-input-9-e469a2d7ff30>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train=torch.tensor(X_train,dtype=torch.float32)
<ipython-input-9-e469a2d7ff30>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test=torch.tensor(X_test,dtype=torch.float32)


In [ ]:
le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train=torch.tensor(y_train,dtype=torch.float32)
y_test=torch.tensor(y_test,dtype=torch.float32)

In [ ]:
import torch.nn as nn
import torch
class Neural(nn.Module):
  def __init__(self,numfeatures):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(numfeatures,100),
        nn.ReLU(),
        nn.Linear(100,10),
        nn.ReLU(),
        nn.Linear(10,1),
        nn.Sigmoid())
  def forward(self,features):
    out=self.network(features)
    return out
# Initialize
model=Neural(X_train.shape[1])
# Forward Pass
model(X_train)


tensor([[0.5938],
        [0.5345],
        [0.5606],
        [0.6101],
        [0.5614],
        [0.5690],
        [0.5434],
        [0.5553],
        [0.5321],
        [0.5447],
        [0.5372],
        [0.4924],
        [0.5582],
        [0.5350],
        [0.5528],
        [0.5591],
        [0.5381],
        [0.5591],
        [0.5715],
        [0.5710],
        [0.5492],
        [0.5647],
        [0.5628],
        [0.6255],
        [0.5564],
        [0.5693],
        [0.5510],
        [0.5496],
        [0.5422],
        [0.5437],
        [0.5509],
        [0.5362],
        [0.5562],
        [0.5531],
        [0.5598],
        [0.5376],
        [0.5435],
        [0.5434],
        [0.5470],
        [0.5405],
        [0.5461],
        [0.5423],
        [0.5482],
        [0.5599],
        [0.5824],
        [0.5546],
        [0.5455],
        [0.5480],
        [0.5640],
        [0.5419],
        [0.5448],
        [0.5935],
        [0.5533],
        [0.5347],
        [0.5594],
        [0

In [ ]:
model.network[0].weight

Parameter containing:
tensor([[ 0.0113, -0.0309,  0.0538,  ..., -0.0460,  0.1764,  0.1512],
        [ 0.0289, -0.0783, -0.0028,  ..., -0.1215,  0.0623, -0.0306],
        [-0.1691, -0.1309, -0.0727,  ...,  0.0942,  0.0764,  0.1201],
        ...,
        [-0.0873,  0.0391, -0.1758,  ..., -0.0478, -0.0724,  0.0107],
        [-0.1009, -0.1193, -0.0430,  ...,  0.1725,  0.1229, -0.0754],
        [-0.0444, -0.1416,  0.1052,  ..., -0.0830,  0.0704,  0.0700]],
       requires_grad=True)

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# Loss Function
Loss_Function=nn.BCELoss()
# Optimization
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
y_train=y_train.view(-1,1)
y_test=y_test.view(-1,1)


Training Pipeline

In [ ]:
num_epochs = 100

for epoch in range(num_epochs):
    y_pred = model(X_train)
    loss = Loss_Function(y_pred, y_train.view(-1,1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.07983953505754471
Epoch: 2, Loss: 0.07932817935943604
Epoch: 3, Loss: 0.07882875204086304
Epoch: 4, Loss: 0.07834067940711975
Epoch: 5, Loss: 0.07786425948143005
Epoch: 6, Loss: 0.07739825546741486
Epoch: 7, Loss: 0.07694292813539505
Epoch: 8, Loss: 0.07649846374988556
Epoch: 9, Loss: 0.07606353610754013
Epoch: 10, Loss: 0.07563700526952744
Epoch: 11, Loss: 0.07521867752075195
Epoch: 12, Loss: 0.07480920106172562
Epoch: 13, Loss: 0.07440832257270813
Epoch: 14, Loss: 0.07401551306247711
Epoch: 15, Loss: 0.07363073527812958
Epoch: 16, Loss: 0.07325442880392075
Epoch: 17, Loss: 0.07288508862257004
Epoch: 18, Loss: 0.07252299040555954
Epoch: 19, Loss: 0.07216776907444
Epoch: 20, Loss: 0.07181894779205322
Epoch: 21, Loss: 0.07147419452667236
Epoch: 22, Loss: 0.07113555073738098
Epoch: 23, Loss: 0.07080310583114624
Epoch: 24, Loss: 0.07047625631093979
Epoch: 25, Loss: 0.07015534490346909
Epoch: 26, Loss: 0.06983988732099533
Epoch: 27, Loss: 0.06952942162752151
Epoch: 28, Lo

In [ ]:
from sklearn.metrics import accuracy_score
with torch.no_grad():
  y_pred_test = model.forward(X_test)
  y_pred_test= (y_pred > 0.5).float()
  accuracy = accuracy_score(y_test, y_pred_test)

In [ ]:
accuracy

0.9649122807017544

In [ ]:
y_pred

tensor([[1.8885e-03],
        [6.8204e-01],
        [4.3323e-02],
        [9.9837e-01],
        [6.8257e-01],
        [1.0000e+00],
        [7.0892e-04],
        [3.6957e-04],
        [1.3414e-01],
        [1.0000e+00],
        [5.3546e-03],
        [1.0000e+00],
        [1.3827e-02],
        [9.0995e-03],
        [8.9645e-04],
        [4.9992e-03],
        [1.7828e-03],
        [1.4436e-02],
        [3.7637e-02],
        [1.5899e-02],
        [9.9995e-01],
        [9.9999e-01],
        [5.8803e-03],
        [9.7739e-01],
        [1.1716e-02],
        [9.9956e-01],
        [4.0963e-03],
        [2.4141e-03],
        [8.7888e-02],
        [2.1365e-02],
        [8.8245e-02],
        [1.0000e+00],
        [9.4198e-04],
        [9.9988e-01],
        [7.8688e-03],
        [6.7423e-03],
        [1.5109e-02],
        [9.9046e-01],
        [1.9547e-01],
        [3.4759e-03],
        [9.8309e-01],
        [1.2392e-03],
        [1.2959e-04],
        [1.0000e+00],
        [2.3290e-05],
        [9