In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## **Creating Tensor**

In [3]:
#Empty
#creates empty tensor returns whatever value already present in memory location
a=torch.empty(2,3)
a

tensor([[7.1760e+22, 7.2250e+28, 1.5766e-19],
        [6.8317e-07, 8.5013e-07, 1.7153e-07]])

In [4]:
#check type
a.type()

'torch.FloatTensor'

In [5]:
#Zeros Tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#Ones Tensor
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#Random Tensor
torch.rand(2,3)

tensor([[0.1322, 0.9657, 0.0290],
        [0.9928, 0.6956, 0.8383]])

In [9]:
#use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
torch.tensor([[1,2,3,4]
            ,[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [27]:
#Arange
print('using arange',torch.arange(1,10,2))

#linspace
print('using linspace',torch.linspace(0,10,5))

#Eye
print('using eye :-\n',torch.eye(5))

#Using Full
print("using full ->", torch.full((3, 3), 5))

using arange tensor([1, 3, 5, 7, 9])
using linspace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye :-
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## **Tensor Shapes**

In [28]:
a=torch.tensor([[1,2,3,4,5,6,7,8,9],
                [1,2,3,4,5,6,7,8,9]])

In [32]:
a.shape

torch.Size([2, 9])

In [33]:
torch.empty_like(a)

tensor([[3617902575710646583, 7454421801564381753, 2322206376936961119,
         7310597164893758754, 3180237793526116959, 7020674649171501600,
         8319593408446489965, 3180215807337460325, 8028074750225097248],
        [3834642605949985390, 3762807392788821093, 7305455646603884342,
         7233969806366881335, 3180167376527243108, 4189022153932546592,
         3543545871972049440, 4194312865738534193, 3618693115226501169]])

In [34]:
torch.zeros_like(a)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
torch.ones_like(a)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [36]:
torch.rand_like(a)
#This cannot happen because torch.rand() puts float value in tensor and our 'a' tensor is long

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

## **Tensor DataTypes**

In [38]:
#Find Dtype
a.dtype

torch.int64

In [39]:
#Assingning Datatypes
a=torch.tensor([1.0,2.3,4.6,7.5],dtype=torch.int64)
a

tensor([1, 2, 4, 7])

In [40]:
#Converting tensor datatype using to()
a.to(torch.float64)

tensor([1., 2., 4., 7.], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## **1)Scalar Operation**

In [41]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
x+10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [44]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [45]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [46]:
x|2

tensor([[3, 2, 3],
        [6, 7, 6]])

In [47]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

## **ElementWise Operation**

In [49]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [50]:
a+b

tensor([[1.1260, 1.3614, 1.6819],
        [0.5626, 1.8200, 1.1675]])

In [51]:
a*b

tensor([[0.2231, 0.4506, 0.6972],
        [0.0572, 0.8275, 0.3407]])

In [53]:
a/b

tensor([[0.2951, 1.3980, 1.2694],
        [0.3102, 1.0555, 1.0343]])

In [54]:
a**b

tensor([[0.3065, 0.8770, 0.9558],
        [0.4208, 0.9419, 0.7413]])

In [55]:
c=torch.tensor([[1,-2,-3],
                [-2,-5,-9]])
c

tensor([[ 1, -2, -3],
        [-2, -5, -9]])

In [56]:
c.abs()

tensor([[1, 2, 3],
        [2, 5, 9]])

In [57]:
c.neg()

tensor([[-1,  2,  3],
        [ 2,  5,  9]])

In [60]:
d=torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [61]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [63]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [64]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [65]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## **Reduction Operation**

In [73]:
e=torch.tensor([[1,2,3,4],
                [5,6,7,8]])

In [74]:
#sum
torch.sum(e)

tensor(36)

In [75]:
#sum along columns
torch.sum(e,dim=0)

tensor([ 6,  8, 10, 12])

In [76]:
#sum along rows
torch.sum(e,dim=1)

tensor([10, 26])

In [78]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [90]:
#mean
torch.mean(e.to(torch.float32))
#mean along col
torch.mean(e.to(torch.float64), dim=0)

tensor([3., 4., 5., 6.], dtype=torch.float64)

In [91]:
# median
torch.median(e)

tensor(4)

In [92]:
# max and min
torch.max(e)
torch.min(e)

tensor(1)

In [93]:
# product
torch.prod(e)

tensor(40320)

In [95]:
# standard deviation
torch.std(e.to(torch.float64))

tensor(2.4495, dtype=torch.float64)

In [99]:
# variance
torch.var(e.to(torch.float64))

tensor(6., dtype=torch.float64)

In [100]:
# argmax
torch.argmax(e)

tensor(7)

In [101]:
# argmin
torch.argmin(e)

tensor(0)

## Matrix **Operations**

In [102]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 6, 9],
        [6, 3, 1]])
tensor([[9, 3],
        [1, 9],
        [7, 9]])


In [103]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[132, 156],
        [ 64,  54]])

In [106]:
vec1=torch.tensor([1,2,3,4,5])
vec2=torch.tensor([1,2,3,4,5])
torch.dot(vec1,vec2)

tensor(55)

In [107]:
#transpose
torch.transpose(f,0,1)

tensor([[7, 6],
        [6, 3],
        [9, 1]])

In [108]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 0., 5.],
        [9., 3., 4.],
        [9., 6., 2.]])

In [109]:
# determinant
torch.det(h)

tensor(99.0000)

In [110]:
# inverse
torch.inverse(h)

tensor([[-0.1818,  0.3030, -0.1515],
        [ 0.1818, -0.4141,  0.3737],
        [ 0.2727, -0.1212,  0.0606]])

# **Comparison operations**

In [114]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 0, 9],
        [6, 9, 5]])
tensor([[4, 8, 8],
        [6, 0, 0]])


In [115]:
i>j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [116]:
i==j

tensor([[False, False, False],
        [ True, False, False]])

In [117]:
i!=j

tensor([[ True,  True,  True],
        [False,  True,  True]])

# **Special Function**

In [127]:
k=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
k

tensor([[8., 9., 1.],
        [8., 8., 8.]])

In [122]:
k.exp()

tensor([[2.9810e+03, 2.7183e+00, 4.0343e+02],
        [1.0966e+03, 7.3891e+00, 2.9810e+03]])

In [123]:
k.relu()

tensor([[8., 1., 6.],
        [7., 2., 8.]])

In [124]:
k.sigmoid()

tensor([[0.9997, 0.7311, 0.9975],
        [0.9991, 0.8808, 0.9997]])

In [125]:
k.tanh()

tensor([[1.0000, 0.7616, 1.0000],
        [1.0000, 0.9640, 1.0000]])

# **Inplace Function**

In [128]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])
tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])


In [129]:
m.add_(n)

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

In [133]:
torch.relu_(m)

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

In [134]:
torch.sigmoid_(m)

tensor([[0.5666, 0.7169, 0.7311],
        [0.8149, 0.7853, 0.7365]])

## **## Copying a Tensor**

In [135]:
a = torch.rand(2,3)
a

tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [136]:
b=a

In [137]:
b

tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [140]:
id(b)

135938174341888

In [141]:
id(a)

135938174341888

In [142]:
b=a.clone()

In [143]:
id(b)

135938173489600

In [144]:
id(a)

135938174341888