In [1]:
import torch
torch.rand(2,2)

tensor([[0.7804, 0.8111],
        [0.6109, 0.2298]])

## **Reshaping,Stacking,Sqeezing and Unsqueezing**

* Reshaping-reshapes an input tensor to a dedined shape
* View-Return a view of input tensor of certain shape but keeps the same memory as original
* Stacking-Combines Multiple tensors on top of each other (vstack) or for side by side (hstack)
* Sqeez- Removes all '1' Dimension from tensor
* Unsqeez- add a 1 dimension to target tensor
* Permute-Return a view of the input with dimension permuted(swapped)in certain way

In [2]:
x=torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [3]:
#Reshape
print(x.reshape(5,2),end='\n')
print(x.reshape(2,5),end='\n')
print(x.reshape(10,1),end='\n')

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])


In [4]:
#View
z=x.view(5,2)
z

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [5]:
#Stack
x_stacked_verticle=torch.stack([x,x,x,x],dim=0)
x_stacked_horizontal=torch.stack([x,x,x,x],dim=1)
print(x_stacked_verticle,x_stacked_horizontal,sep='\n')

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


In [6]:
#Squeez
x_reshaped=x.reshape(1,10)
x_reshaped,torch.squeeze(x_reshaped)

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [7]:
#Unsqeez(Adds One dimension)
torch.unsqueeze(x_stacked_verticle,dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])

In [8]:
#Torch.Permute
#x=torch.rand(height,width,colour_channels)
x=torch.rand(224,224,3)
x
print('Original:',x,end='\n')
#Permute(swap)
print('Permuted',x.permute(2,0,1))

print('Original Shape:',x.shape)
print('Permuted Shape:',x.permute(2,0,1).shape)

Original: tensor([[[0.5011, 0.0820, 0.5942],
         [0.5203, 0.6999, 0.3051],
         [0.6648, 0.5412, 0.5233],
         ...,
         [0.2506, 0.0741, 0.1092],
         [0.4863, 0.8452, 0.9048],
         [0.1886, 0.0611, 0.0201]],

        [[0.5996, 0.8061, 0.6700],
         [0.1619, 0.9321, 0.7920],
         [0.2756, 0.1212, 0.3048],
         ...,
         [0.1872, 0.7640, 0.5871],
         [0.3808, 0.7811, 0.4614],
         [0.6674, 0.3172, 0.3566]],

        [[0.5129, 0.9447, 0.8758],
         [0.6912, 0.5756, 0.8735],
         [0.4158, 0.8130, 0.8714],
         ...,
         [0.6108, 0.3809, 0.1253],
         [0.5832, 0.4753, 0.5970],
         [0.5363, 0.4448, 0.6133]],

        ...,

        [[0.3126, 0.8131, 0.0755],
         [0.5660, 0.5388, 0.8317],
         [0.0493, 0.7105, 0.6474],
         ...,
         [0.9298, 0.2705, 0.8224],
         [0.6614, 0.6525, 0.6523],
         [0.9015, 0.8580, 0.7908]],

        [[0.4047, 0.7169, 0.6872],
         [0.3880, 0.5011, 0.7597],
  

# **Indexing**

* Indexing with pytorch is same as Numpy

In [17]:
#create tensor
x=torch.arange(1,10)
print(x)
x=x.reshape(1,3,3)
print(x,x.size())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [18]:
#index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
#index on middle brackets
x[0][0]

tensor([1, 2, 3])

In [20]:
#index on last dimension
x[0][0][0]

tensor(1)

In [21]:
x[1][1][1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [23]:
x[0][1]

tensor([4, 5, 6])

In [25]:
x[0][1][0]

tensor(4)

In [36]:
#We can also use ':' to select all of target dimension
print(x[:,0,1],end='\n\n')
print(x[:,:,:],end='\n\n')
print(x[:,:,0],end='\n\n')
print(x[:,:1,:],end='\n\n')
print(x[:,:2,:2],end='\n\n')

tensor([2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([[1, 4, 7]])

tensor([[[1, 2, 3]]])

tensor([[[1, 2],
         [4, 5]]])



In [48]:
#Index on x to return 9
print(x)
print(x[:,2:,2:].reshape(1))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([9])
