In [ ]:
import torch
import torch.nn as nn

In [ ]:
class NN(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,x):
    out=self.network(x)
    return out

In [ ]:
features=torch.randn(100,5)

In [ ]:
model=NN(features.shape[1])
model(features)

tensor([[0.4955],
        [0.5117],
        [0.5258],
        [0.4905],
        [0.5258],
        [0.5348],
        [0.5249],
        [0.5100],
        [0.5233],
        [0.5262],
        [0.5335],
        [0.5258],
        [0.5121],
        [0.5258],
        [0.5076],
        [0.5258],
        [0.5514],
        [0.5279],
        [0.5202],
        [0.5132],
        [0.5219],
        [0.4944],
        [0.5222],
        [0.4865],
        [0.5286],
        [0.5190],
        [0.5083],
        [0.5262],
        [0.5087],
        [0.5258],
        [0.5258],
        [0.5101],
        [0.5258],
        [0.5205],
        [0.5258],
        [0.5072],
        [0.5096],
        [0.5259],
        [0.4984],
        [0.4857],
        [0.4836],
        [0.5258],
        [0.5153],
        [0.5274],
        [0.5258],
        [0.5436],
        [0.5147],
        [0.5458],
        [0.5258],
        [0.4991],
        [0.5135],
        [0.4953],
        [0.5222],
        [0.5513],
        [0.5094],
        [0

In [ ]:
print(model.network[0].weight)  # Weights of the first Linear layer
print(model.network[0].bias)

print(model.network[2].weight)  # Weights of the first Linear layer
print(model.network[2].bias)

Parameter containing:
tensor([[-0.0522, -0.0321,  0.2050,  0.3214,  0.0570],
        [ 0.0390, -0.0936,  0.3586, -0.2731,  0.1291],
        [ 0.0448,  0.1437,  0.4111, -0.2202, -0.1506]], requires_grad=True)
Parameter containing:
tensor([ 0.2298, -0.1133,  0.1145], requires_grad=True)
Parameter containing:
tensor([[-0.1418,  0.1294,  0.0014]], requires_grad=True)
Parameter containing:
tensor([0.1031], requires_grad=True)


In [ ]:
from torchinfo import summary

summary(model, input_size=(100, 5))

Layer (type:depth-idx)                   Output Shape              Param #
NN                                       [100, 1]                  --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 3]                  18
│    └─ReLU: 2-2                         [100, 3]                  --
│    └─Linear: 2-3                       [100, 1]                  4
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [ ]:
!pip install torchinfo